(function() {var implementors = {};
implementors["strymon_job"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"strymon_job/operators/publish/enum.Partition.html\" title=\"enum strymon_job::operators::publish::Partition\">Partition</a>",];
implementors["strymon_model"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"strymon_model/struct.TopicId.html\" title=\"struct strymon_model::TopicId\">TopicId</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"strymon_model/struct.JobId.html\" title=\"struct strymon_model::JobId\">JobId</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"strymon_model/struct.ExecutorId.html\" title=\"struct strymon_model::ExecutorId\">ExecutorId</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"strymon_model/struct.Publication.html\" title=\"struct strymon_model::Publication\">Publication</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"strymon_model/struct.Subscription.html\" title=\"struct strymon_model::Subscription\">Subscription</a>",];
implementors["strymon_rpc"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"strymon_rpc/coordinator/catalog/enum.CatalogRPC.html\" title=\"enum strymon_rpc::coordinator::catalog::CatalogRPC\">CatalogRPC</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"strymon_rpc/coordinator/enum.CoordinatorRPC.html\" title=\"enum strymon_rpc::coordinator::CoordinatorRPC\">CoordinatorRPC</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"strymon_rpc/coordinator/struct.JobToken.html\" title=\"struct strymon_rpc::coordinator::JobToken\">JobToken</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"strymon_rpc/executor/enum.ExecutorRPC.html\" title=\"enum strymon_rpc::executor::ExecutorRPC\">ExecutorRPC</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
