(function() {var implementors = {};
implementors["strymon_communication"] = ["impl <a class=\"trait\" href=\"https://docs.rs/futures/0.1/futures/stream/trait.Stream.html\" title=\"trait futures::stream::Stream\">Stream</a> for <a class=\"struct\" href=\"strymon_communication/transport/struct.Receiver.html\" title=\"struct strymon_communication::transport::Receiver\">Receiver</a>","impl <a class=\"trait\" href=\"https://docs.rs/futures/0.1/futures/stream/trait.Stream.html\" title=\"trait futures::stream::Stream\">Stream</a> for <a class=\"struct\" href=\"strymon_communication/transport/struct.Listener.html\" title=\"struct strymon_communication::transport::Listener\">Listener</a>","impl&lt;N:&nbsp;<a class=\"trait\" href=\"strymon_communication/rpc/trait.Name.html\" title=\"trait strymon_communication::rpc::Name\">Name</a>&gt; <a class=\"trait\" href=\"https://docs.rs/futures/0.1/futures/stream/trait.Stream.html\" title=\"trait futures::stream::Stream\">Stream</a> for <a class=\"struct\" href=\"strymon_communication/rpc/struct.Incoming.html\" title=\"struct strymon_communication::rpc::Incoming\">Incoming</a>&lt;N&gt;","impl&lt;N:&nbsp;<a class=\"trait\" href=\"strymon_communication/rpc/trait.Name.html\" title=\"trait strymon_communication::rpc::Name\">Name</a>&gt; <a class=\"trait\" href=\"https://docs.rs/futures/0.1/futures/stream/trait.Stream.html\" title=\"trait futures::stream::Stream\">Stream</a> for <a class=\"struct\" href=\"strymon_communication/rpc/struct.Server.html\" title=\"struct strymon_communication::rpc::Server\">Server</a>&lt;N&gt;",];
implementors["strymon_coordinator"] = ["impl <a class=\"trait\" href=\"https://docs.rs/futures/0.1/futures/stream/trait.Stream.html\" title=\"trait futures::stream::Stream\">Stream</a> for <a class=\"struct\" href=\"strymon_coordinator/catalog/struct.Service.html\" title=\"struct strymon_coordinator::catalog::Service\">Service</a>",];
implementors["strymon_job"] = ["impl&lt;T, D&gt; <a class=\"trait\" href=\"https://docs.rs/futures/0.1/futures/stream/trait.Stream.html\" title=\"trait futures::stream::Stream\">Stream</a> for <a class=\"struct\" href=\"strymon_job/operators/subscribe/struct.Subscription.html\" title=\"struct strymon_job::operators::subscribe::Subscription\">Subscription</a>&lt;T, D&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;T: <a class=\"trait\" href=\"strymon_job/operators/trait.RemoteTimestamp.html\" title=\"trait strymon_job::operators::RemoteTimestamp\">RemoteTimestamp</a>,<br>&nbsp;&nbsp;&nbsp;&nbsp;D: <a class=\"trait\" href=\"https://docs.rs/serde/1.0.33/serde/de/trait.DeserializeOwned.html\" title=\"trait serde::de::DeserializeOwned\">DeserializeOwned</a>,&nbsp;</span>","impl&lt;N:&nbsp;<a class=\"trait\" href=\"strymon_communication/rpc/trait.Name.html\" title=\"trait strymon_communication::rpc::Name\">Name</a>&gt; <a class=\"trait\" href=\"https://docs.rs/futures/0.1/futures/stream/trait.Stream.html\" title=\"trait futures::stream::Stream\">Stream</a> for <a class=\"struct\" href=\"strymon_job/operators/service/struct.Service.html\" title=\"struct strymon_job::operators::service::Service\">Service</a>&lt;N&gt;",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
